OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Dyno
    Domain: dyno.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 3