version: '2'

networks:
  ca-dyno:

services:

  ca_dyno:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.dyno
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=1010
    ports:
      - 1010:1010
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../consortium/fabric-ca/dyno:etc/hyperledger/fabric-ca-server
    container_name: ca.dyno
    networks:
      - ca-dyno