# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.dyno.example.com:
    container_name: peer0.dyno.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dyno.example.com
      - CORE_PEER_ADDRESS=peer0.dyno.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.dyno.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dyno.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dyno.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dyno.example.com/peers/peer0.dyno.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dyno.example.com/peers/peer0.dyno.example.com/tls:/etc/hyperledger/fabric/tls
        - peer0.dyno.example.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.dyno.example.com:
    container_name: peer1.dyno.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.dyno.example.com
      - CORE_PEER_ADDRESS=peer1.dyno.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.dyno.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.dyno.example.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.dyno.example.com:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dyno.example.com/peers/peer1.dyno.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/dyno.example.com/peers/peer1.dyno.example.com/tls:/etc/hyperledger/fabric/tls
        - peer1.dyno.example.com:/var/hyperledger/production
    ports:
      - 8051:8051

  couchdb0: 
    container_name: couchdb0
    extends: 
      file: peer-base.yaml
      service: couchdb-base
    environment:
      - COUCHDB_USER=dyno
      - COUCHDB_PASSWORD=root
    ports:
      - 5984:5984

  couchdb1: 
    container_name: couchdb1
    extends: 
      file: peer-base.yaml
      service: couchdb-base
    environment:
      - COUCHDB_USER=dyno
      - COUCHDB_PASSWORD=root
    ports:
      - 5985:5985